hombre(bart).
hombre(homero).
hombre(abraham).
hombre(herb).
hombre(clancy).
mujer(lisa).
mujer(maggie).
mujer(marge).
mujer(selma).
mujer(patty).
mujer(mona).
mujer(jackeline).
mujer(ling).
padre(bart,homero).
padre(lisa,homero).
padre(maggie,homero).
padre(homero,abraham).
padre(herb,abraham).
padre(marge,clancy).
padre(patty,clancy).
padre(selma,clancy).
madre(bart,marge).
madre(lisa,marge).
madre(maggie,marge).
madre(homero,mona).
madre(herb,mona).
madre(marge,jackeline).
madre(patty,jackeline).
madre(selma,jackeline).
madre(ling,selma).

abuelo(X,Y):-(padre(X,Z);madre(X,Z)),padre(Z,Y).
abuela(X,Y):-(padre(X,Z);madre(X,Z)),madre(Z,Y).
nieto(X,Y):-hombre(Y),(abuelo(Y,X);abuela(Y,X)).
nieta(X,Y):-mujer(Y),(abuelo(Y,X);abuela(Y,X)).
hermano(X,Y):-hombre(Y),((padre(X, Z),padre(Y,Z));(madre(X, Z),madre(Y,Z))).
hermana(X,Y):-mujer(Y),((padre(X, Z),padre(Y,Z));(madre(X, Z),madre(Y,Z))).
tia(X,Y):-hermana(Z,Y),(padre(X,Z);madre(X,Z)).
primo(X,Y):-hombre(Y),(padre(Y,W);madre(Y,W)),(hermano(W,Z);hermana(W,Z)),(padre(X,Z);madre(X,Z)).
sobrino(X,Y):-hombre(Y),(padre(Y,Z);madre(Y,Z)),(hermano(X,Z);hermana(X,Z)).
pareja(X,Y):-(padre(Z,X);madre(Z,X)),(padre(Z,Y);madre(Z,Y)).
